language: python
python:
  - "2.7"
  - "3.3"
before_install:
 - sudo apt-get install -qq python-numpy python-scipy python-sklearn python-matplotlib python-biopython python-networkx python3-matplotlib python3-numpy python3-scipy python3-networkx
 # Workaround for a permissions issue with Travis virtual machine images
 # that breaks Python's multiprocessing:
 # https://github.com/travis-ci/travis-cookbooks/issues/155
 - sudo rm -rf /dev/shm
 - sudo ln -s /run/shm /dev/shm
install: pip install -r .travis.require --use-mirrors
script:
 - bash test/.travis_single.sh
 - bash test/.travis_mutant.sh
 - bash test/.travis_pangenome.sh
 - bash test/.travis_misc.sh
